### ISSUE TITLE
如何判断当前页面是否基于opensumi/core，从而判断是否让opensumi devtools运行？

### ISSUE THREAD

**Issue by tyn1998** [tyn1998/opensumi-devtools#5]
最简单的是opensumi/core往全局window对象扔一个标识符。

**Comment by tyn1998** [comment]
React devtools是怎么做的？

就是靠全局变量，请见[这个回答](https://stackoverflow.com/a/46808361/10369621)。

**Comment by erha19** [comment]
@tyn1998 加全局变量是可以的，比较合理也比较准确

**Comment by tyn1998** [comment]
React Devtools一旦打开后**不会处理**当前页面改变的情况（前进后退到别的页面、从收藏夹打开页面、直接输入url改变页面），所以devtools panel会一直保留，即使当前页面没有React。

opensumi devtools可以更加细节一点，利用chrome extension的API，当页面发生变化的时候，重新判断是否要关闭或运行。

当然，也可以不做这个细节处理，毕竟用户只要重新打开一下devtools就行。
