### ISSUE TITLE
将仓库转移到opensumi下

### ISSUE THREAD

**Issue by tyn1998** [tyn1998/opensumi-devtools#52]
要考虑的事情：

- 新仓库的命名
- xxx

**Comment by tyn1998** [comment]
@Yantze @erha19 两位老师好，请问仓库转移可以在什么时机进行？

![image](https://user-images.githubusercontent.com/32434520/186067607-63cda154-1b6c-4961-a8b9-e63ecd45ce99.png)

**Comment by yantze** [comment]
直接用 devtools 就好了

**Comment by yantze** [comment]
1. 你先写一下转移到 opensumi 的组织，然后这边通过后，会变为 opensumi/devtools
2. 之后你会有 devtools 的权限，然后和自己提交代码类似

**Comment by tyn1998** [comment]
好的！

**Comment by erha19** [comment]
@tyn1998 https://github.com/opensumi/devtool 已经建好仓库并给你权限，你可以直接往这个仓库提交代码

**Comment by tyn1998** [comment]
![image](https://user-images.githubusercontent.com/32434520/186304704-cad4c116-a188-4df1-b034-9f168567a4f3.png)

转移仓库需要权限。

@erha19 老师，那是不是说tyn1998/opensumi-devtools的issues和PR都不带走了，在新仓库里直接把main分支推上去？

**Comment by tyn1998** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/32434520/186388243-6016a8e0-4fe9-4f5d-875a-c692948603f3.png">
