### ISSUE TITLE
How electron app loads the devtools extension?

### ISSUE THREAD

**Issue by tyn1998** [tyn1998/opensumi-devtools#55]
Currently, in development, I hard code to load the extension from a local path:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/32434520/185872063-c68fe3fc-56b4-415d-8e04-2ca825541817.png">

Should the devtools be integrated with electron app by importing from a package or other way?

**Comment by tyn1998** [comment]
Hi, @yantze, 你有什么好主意吗？

**Comment by yantze** [comment]
用这个模块去安装 https://www.npmjs.com/package/electron-devtools-installer
