### ISSUE TITLE
[Bug] test fails

### ISSUE THREAD

**Issue by tyn1998** [tyn1998/opensumi-devtools#56]
https://github.com/opensumi/core/runs/7947523164?check_suite_focus=true

![image](https://user-images.githubusercontent.com/32434520/185881411-b1c806b0-de26-4350-9c0f-8ca8401a058b.png)

**Comment by yantze** [comment]
在 utils.ts 里面用的时候，要判断一下 window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__ 是否存在

**Comment by tyn1998** [comment]
OK！

本来是有这一步的，但我以为在ClientApp构造函数里向window注入HOOK就能保证不会undefined。完全没有考虑到测试的时候是分开测的。
